CREATE TABLE T_DELIVER (
  ID_DELIVER INT NOT NULL PRIMARY KEY,
  DELIVER_DATE NVARCHAR2(150) NOT NULL,
  ID_SECTION INT NOT NULL REFERENCES T_SECTION(ID_SECTION),
  ID_MATERIAL INT NOT NULL REFERENCES T_MATERIAL(ID_MATERIAL),
  ID_STORE INT NOT NULL REFERENCES T_STORE(ID_STORE)
)