CREATE TABLE T_SUPPLY (
  ID_SUPPLY INT NOT NULL PRIMARY KEY,
  SUPPLY_DATE NVARCHAR2(150) NOT NULL,
  VOLUME NVARCHAR2(150) NOT NULL,
  ID_CATERER INT NOT NULL REFERENCES T_CATERER(ID_CATERER),
  ID_MATERIAL INT NOT NULL REFERENCES T_MATERIAL(ID_MATERIAL),
  ID_STORE INT NOT NULL REFERENCES T_STORE(ID_STORE)
)