CREATE SEQUENCE SEQ_CATERER
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_DELIVER
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_EMPLOYER
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_GROUP
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_INPRICE
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_MATERIAL
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_MESSURE
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_SECTION
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_STORE
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_SUPPLY
  START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_SURPLUS
  START WITH 1
    INCREMENT BY 1;