INSERT INTO T_SECTION(ID_SECTION,
  NAME,
  ID_EMPLOYER)
VALUES(SEQ_SECTION.NEXTVAL,
  'Изготовление 1',
  '1');

INSERT INTO T_SECTION(ID_SECTION,
  NAME,
  ID_EMPLOYER)
VALUES(SEQ_SECTION.NEXTVAL,
  'Обработка',
  '2');

INSERT INTO T_SECTION(ID_SECTION,
  NAME,
  ID_EMPLOYER)
VALUES(SEQ_SECTION.NEXTVAL,
  'Очистка',
  '3');

INSERT INTO T_SECTION(ID_SECTION,
  NAME,
  ID_EMPLOYER)
VALUES(SEQ_SECTION.NEXTVAL,
  'Проверка',
  '4');

INSERT INTO T_SECTION(ID_SECTION,
  NAME,
  ID_EMPLOYER)
VALUES(SEQ_SECTION.NEXTVAL,
  'ИЗготовление 2',
  '5');
