INSERT INTO T_MATERIAL(ID_MATERIAL,
  name,
  ID_MESSURE)
VALUES(SEQ_MATERIAL.NEXTVAL,
  'Дерево',
  '1');

INSERT INTO T_MATERIAL(ID_MATERIAL,
  name,
  ID_MESSURE)
VALUES(SEQ_MATERIAL.NEXTVAL,
  'Металл',
  '2');

INSERT INTO T_MATERIAL(ID_MATERIAL,
  name,
  ID_MESSURE)
VALUES(SEQ_MATERIAL.NEXTVAL,
  'Ткань',
  '3');

INSERT INTO T_MATERIAL(ID_MATERIAL,
  name,
  ID_MESSURE)
VALUES(SEQ_MATERIAL.NEXTVAL,
  'Пластик',
  '4');

INSERT INTO T_MATERIAL(ID_MATERIAL,
  name,
  ID_MESSURE)
VALUES(SEQ_MATERIAL.NEXTVAL,
  'Бетон',
  '1');