INSERT INTO T_STORE(ID_STORE,
  NAME)
VALUES(SEQ_STORE.NEXTVAL,
  'Qooven');

INSERT INTO T_STORE(ID_STORE,
  NAME)
VALUES(SEQ_STORE.NEXTVAL,
  'MIOBI');

INSERT INTO T_STORE(ID_STORE,
  NAME)
VALUES(SEQ_STORE.NEXTVAL,
  'GreenBa');

INSERT INTO T_STORE(ID_STORE,
  NAME)
VALUES(SEQ_STORE.NEXTVAL,
  'TRIMIC');

INSERT INTO T_STORE(ID_STORE,
  NAME)
VALUES(SEQ_STORE.NEXTVAL,
  'MyShoko');

