INSERT INTO T_MESSURE(ID_MESSURE,
  NAME)
VALUES(SEQ_MESSURE.NEXTVAL,
  'КГ');

INSERT INTO T_MESSURE(ID_MESSURE,
  NAME)
VALUES(SEQ_MESSURE.NEXTVAL,
  'М');

INSERT INTO T_MESSURE(ID_MESSURE,
  NAME)
VALUES(SEQ_MESSURE.NEXTVAL,
  'ШТ');

INSERT INTO T_MESSURE(ID_MESSURE,
  NAME)
VALUES(SEQ_MESSURE.NEXTVAL,
  'ДНИ');

INSERT INTO T_MESSURE(ID_MESSURE,
  NAME)
VALUES(SEQ_MESSURE.NEXTVAL,
  'РУБ');