INSERT INTO T_GROUP(ID_GROUP,
  NAME,
  ID_MATERIAL)
VALUES(SEQ_GROUP.NEXTVAL,
  'Group1',
  '4');

INSERT INTO T_GROUP(ID_GROUP,
  NAME,
  ID_MATERIAL)
VALUES(SEQ_GROUP.NEXTVAL,
  'Group2',
  '5');

INSERT INTO T_GROUP(ID_GROUP,
  NAME,
  ID_MATERIAL)
VALUES(SEQ_GROUP.NEXTVAL,
  'Group3',
  '6');

INSERT INTO T_GROUP(ID_GROUP,
  NAME,
  ID_MATERIAL)
VALUES(SEQ_GROUP.NEXTVAL,
  'Group4',
  '7');

INSERT INTO T_GROUP(ID_GROUP,
  NAME,
  ID_MATERIAL)
VALUES(SEQ_GROUP.NEXTVAL,
  'Group5',
  '8')