INSERT INTO T_DELIVER(ID_DELIVER,
  DELIVER_DATE,
  ID_SECTION,
  ID_MATERIAL,
  ID_STORE)
VALUES(SEQ_DELIVER.NEXTVAL,
  '21.04.2016',
  '22',
  '4',
  '1');

INSERT INTO T_DELIVER(ID_DELIVER,
  DELIVER_DATE,
  ID_SECTION,
  ID_MATERIAL,
  ID_STORE)
VALUES(SEQ_DELIVER.NEXTVAL,
  '3.06.2016',
  '23',
  '5',
  '2');

INSERT INTO T_DELIVER(ID_DELIVER,
  DELIVER_DATE,
  ID_SECTION,
  ID_MATERIAL,
  ID_STORE)
VALUES(SEQ_DELIVER.NEXTVAL,
  '18.07.2016',
  '24',
  '6',
  '3');

INSERT INTO T_DELIVER(ID_DELIVER,
  DELIVER_DATE,
  ID_SECTION,
  ID_MATERIAL,
  ID_STORE)
VALUES(SEQ_DELIVER.NEXTVAL,
  '29.10.2016',
  '25',
  '7',
  '4');

INSERT INTO T_DELIVER(ID_DELIVER,
  DELIVER_DATE,
  ID_SECTION,
  ID_MATERIAL,
  ID_STORE)
VALUES(SEQ_DELIVER.NEXTVAL,
  '10.12.2016',
  '26',
  '8',
  '5');

